#!/bin/sh
# Install all dotfiles into the home directory

DOTFILESDIRREL=$(dirname $0)
cd $DOTFILESDIRREL/..
DOTFILESDIR=$(pwd -P)
VSCODE="$HOME/Library/Application Support/Code/User"

for DOTFILE in dotfiles/*; do
  HOMEFILE="$HOME/.$DOTFILE"
  [ -d $DOTFILE ] && DOTFILE="$DOTFILE/"
  DIRFILE="$DOTFILESDIR/$DOTFILE"

  echo $DOTFILE | grep -q '\.sh' &&
       HOMEFILE="$HOME/.$(echo $DOTFILE | sed -e 's/\.sh//')"

  if echo $DOTFILE | grep -q 'rubocop.yml'
  then
    HOMEFILE="$HOME/Documents/.rubocop.yml"
  fi

  if [ -L "$HOMEFILE" ] && ! [ -d $DOTFILE ]
  then
    ln -sfv "$DIRFILE" "$HOMEFILE"
  else
    rm -rv "$HOMEFILE"
    ln -sv "$DIRFILE" "$HOMEFILE"
  fi
done