#!/bin/sh
# Post strap, perform additional configuration and installation.

# Install Oh My ZSH
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# macOS specific configurations
if [ "$(uname)" = "Darwin" ]; then
	defaults write -g ApplePressAndHoldEnabled -bool false
fi
